version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '12:00'
    groups:
      patch-updates:
        update-types: ['patch']
