version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '12:00'
    commit-message:
      prefix: '🌱 update'
    open-pull-requests-limit: 20
    groups:
      patch-updates:
        update-types: ['patch']
